version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/edgexfoundry/go-mod-core-contracts/*"
        # Included when device-sdk-go is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-messaging/*"
        # Included when device-sdk-go is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-registry/*"
        # Included when device-sdk-go is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-secrets/*"
        # Included when device-sdk-go is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-bootstrap/*"
        # Included when device-sdk-go is updated
